### ISSUE TITLE
While using this tool an error occurs

### ISSUE THREAD

**Issue by ghost** [CirnoV/palworld-guild-save-fix#2]
![image](https://github.com/CirnoV/palworld-guild-save-fix/assets/60777728/eecb5222-a759-4bc1-8449-6baea51880f5)

here is my saved file my game version is .014.0

[1BE8B1204FF0D29E9B68928308A3823F.zip](https://github.com/CirnoV/palworld-guild-save-fix/files/14137760/1BE8B1204FF0D29E9B68928308A3823F.zip)
Hope you can help me.Thank you.

I am a user from China so my english might not be quite well.I hope you can understand what i say

**Comment by CirnoV** [comment]
This save file seems to be affected by a different type of corruption. Typically, 'guild leaving bugs' refer to save file corruption where guild data is intact, but the save data for individual guild members is corrupted. However, in this case, there is only one guild on the server, and it consists of just one member.

In this case, it seems that the character's name cannot be retrieved from the guild data, making it difficult to recover the character data using this tool.

Based on the logs, it seems that the `03A73161000000000000000000000000.sav`, `8AA8E70A000000000000000000000000.sav`, and `9BDFF4AC000000000000000000000000.sav` are corrupted.

To proceed with the manual recovery process, please follow the steps outlined in the following link: https://www.reddit.com/r/Palworld/comments/19f71p7/guild_leave_bug_fix_for_dedicated_servers/
